/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8W05bmFzMel
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"

export function page() {
  return (
    <div className="dark:bg-background dark:text-foreground">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-md dark:bg-background/80">
        <div className="container flex items-center h-16 px-4 md:px-6">
          <nav className="flex-col hidden gap-6 text-lg font-medium md:flex md:flex-row md:items-center md:gap-5 md:text-sm lg:gap-6">
            <Link href="#" className="flex items-center gap-2 text-lg font-semibold md:text-base" prefetch={false}>
              <Package2Icon className="w-6 h-6" />
              <span className="sr-only">Acme Inc</span>
            </Link>
            <Link href="#" className="font-bold text-primary dark:text-primary-foreground" prefetch={false}>
              Anime
            </Link>
            <Link href="#" className="text-muted-foreground dark:text-muted-foreground" prefetch={false}>
              Manga
            </Link>
            <Link href="#" className="text-muted-foreground dark:text-muted-foreground" prefetch={false}>
              Trending
            </Link>
          </nav>
          <div className="flex items-center w-full gap-4 md:ml-auto md:gap-2 lg:gap-4">
            <form className="flex-1 ml-auto sm:flex-initial">
              <div className="relative">
                <SearchIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground dark:text-muted-foreground" />
                <Input
                  type="search"
                  placeholder="Search anime and manga..."
                  className="pl-8 sm:w-[300px] md:w-[200px] lg:w-[300px] dark:bg-background dark:border-input dark:text-foreground"
                />
              </div>
            </form>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="rounded-full dark:bg-background dark:text-foreground">
                  <img
                    src="/placeholder.svg"
                    width="32"
                    height="32"
                    className="rounded-full"
                    alt="Avatar"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }}
                  />
                  <span className="sr-only">Toggle user menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Profile</DropdownMenuItem>
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main>
        <section className="pt-20 md:pt-24 lg:pt-32">
          <div className="container">
            <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-[1fr_400px]">
              <div className="flex flex-col justify-center space-y-6">
                <div>
                  <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-muted dark:text-muted-foreground">
                    Featured
                  </div>
                  <h1 className="mt-2 text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                    Dive into the World of Anime and Manga
                  </h1>
                  <p className="mt-4 text-muted-foreground md:text-xl dark:text-muted-foreground">
                    Explore the latest and greatest anime and manga content, updated daily.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-primary dark:text-primary-foreground"
                    prefetch={false}
                  >
                    Explore Anime
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:border-input dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                    prefetch={false}
                  >
                    Explore Manga
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width={800}
                height={600}
                alt="Anime hero image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted dark:bg-muted">
          <div className="container">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-muted dark:text-muted-foreground">
                  New Releases
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Discover the Latest Anime and Manga</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground">
                  Check out the newest additions to our library, updated daily.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="New Release 1"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  Attack on Titan: Final Season
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  The epic conclusion to the hit anime series.
                </div>
              </Link>
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="New Release 2"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  Spy x Family: Part 2
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  The thrilling continuation of the hit spy anime.
                </div>
              </Link>
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="New Release 3"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  Chainsaw Man: Part 1
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  The highly anticipated anime adaptation of the hit manga.
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-muted dark:text-muted-foreground">
                  Popular This Week
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The Most Watched Anime and Manga</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-muted-foreground">
                  Check out the most popular anime and manga content on our platform this week.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Popular 1"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  Demon Slayer: Kimetsu no Yaiba
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  The thrilling story of a young boy's quest to avenge his family.
                </div>
              </Link>
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Popular 2"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  Jujutsu Kaisen
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  A thrilling supernatural action anime about cursed spirits.
                </div>
              </Link>
              <Link
                href="#"
                className="group grid h-auto w-full justify-start gap-1 rounded-md bg-background p-4 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground focus:outline-none disabled:pointer-events-none disabled:opacity-50 dark:bg-background dark:text-foreground dark:hover:bg-accent dark:hover:text-accent-foreground"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={450}
                  alt="Popular 3"
                  className="aspect-[2/3] overflow-hidden rounded-md object-cover"
                />
                <div className="text-sm font-medium leading-none group-hover:underline dark:text-foreground">
                  My Hero Academia
                </div>
                <div className="line-clamp-2 text-sm leading-snug text-muted-foreground dark:text-muted-foreground">
                  The story of a young boy's journey to become the greatest hero.
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted dark:bg-muted">
          <div className="container">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-muted dark:text-muted-foreground">
                  Trending
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  The Hottest Anime and Manga Right Now
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-" />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
